version: 0.0
os: linux
files:
  - source: /scripts # CodeDeploy 아티팩트 내의 scripts 폴더
    destination: /home/ubuntu/scripts # EC2 인스턴스의 특정 경로로 복사

permissions:
  - object: /home/ubuntu/scripts # 복사된 scripts 폴더에 권한 부여
    pattern: "**"
    owner: ubuntu
    group: ubuntu
    mode: 755

hooks:
  ApplicationStop: # 컨테이너를 먼저 중지합니다.
    - location: scripts/stop_container.sh
      timeout: 60
      runas: ubuntu
  BeforeInstall: # 선택 사항: 이전 컨테이너 이미지 삭제 등
    - location: scripts/clean_old_images.sh
      timeout: 60
      runas: ubuntu
  ApplicationStart: # Docker 컨테이너를 실행합니다. (환경변수 주입)
    - location: scripts/start_container.sh
      timeout: 300 # 컨테이너 시작에 시간 소요될 수 있으므로 여유롭게 설정
      runas: ubuntu
  ValidateService: # 서비스가 정상적으로 올라왔는지 확인합니다.
    - location: scripts/validate_service.sh
      timeout: 180
      runas: ubuntu
