version: 0.0
os: linux
files:
  - source: / # 전체 배포 번들을 복사
    destination: /opt/codedeploy-deployment # EC2 인스턴스의 임시 디렉토리
hooks:
  BeforeInstall:
    - location: scripts/stop_container.sh # 기존 Docker 컨테이너 중지
      timeout: 180
      runas: root
  ApplicationStart:
    - location: scripts/start_container.sh # 새 Docker 컨테이너 시작
      timeout: 360
      runas: root
  ValidateService:
    - location: scripts/validate_service.sh # 헬스 체크
      timeout: 300
      runas: root
