spring:
  # H2 관련 자동 구성 제외
   autoconfigure:
     exclude:
       - org.springframework.boot.autoconfigure.h2.H2ConsoleAutoConfiguration # H2 콘솔 자동 구성
       - org.springframework.boot.autoconfigure.jdbc.h2.H2AutoConfiguration # H2 JDBC 자동 구성 

   datasource:
      driver-class-name: org.mariadb.jdbc.Driver

   jpa:
      hibernate:
         ddl-auto: create
      properties:
         hibernate:
            format_sql: true
            show_sql: true
            defer-datasource-initialization: true

   batch:
      jdbc:
         initialize-schema: always # Spring Batch 메타데이터 테이블 자동 생성
         platform: mariadb
      job:
         enabled: false # 애플리케이션 시작 시 Job 자동 실행 방지 (수동 실행 위함)

jwt:
  secret: ${JWT_SECRET_KEY} 
  access-token-validity-in-seconds: ${JWT_ACCESS_TOKEN_VALIDITY_IN_SECONDS}
  refresh-token-validity-in-seconds: ${JWT_REFRESH_TOKEN_VALIDITY_IN_SECONDS}

server:
  port: 8080
  servlet:
    context-path: /studio-recipe


front:
  url: ${FRONT_URL}

logging:
  level:
    org.hibernate.SQL: debug
    org.springframework.security: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: trace
    com.recipe: debug
